runtime: go
api_version: go1

skip_files:
- ^node_modules(/.*)?
- ^src(/.*)?

handlers:
- url: /images/(.*\.(gif|png|jpg))$
  static_files: static/images/\1
  upload: static/images/.*\.(gif|png|jpg)$

- url: /.*
  script: _go_app